## Deploy service golang with Ansible
# ansible-playbook playbooks/pl_grafana_local.yml
---
- name: Docker Grafana deploy
  hosts: localhost
  connection: local 
  become: true
  gather_facts: false

  tasks:
    - name: Create project path and subfolder for container
      file:
        path: "../data/grafana_data"
        mode: 0755
        group: 472
        owner: 472
        recurse: true
        state: directory

    - name: Copy files provisioning
      ansible.builtin.copy:
        src: ../grafana/provisioning
        dest: ../data
        mode: 0755
        group: 472
        owner: 472
        remote_src: true

    - name: Container Grafana deploy
      community.docker.docker_compose:
        project_src: ../grafana

