## Deploy service golang with Ansible
# ansible-playbook playbooks/pl_efk_local.yml

# Configuration EFK
# docker exec -it elasticsearch /usr/share/elasticsearch/bin/elasticsearch-reset-password -i -u elastic
# docker exec -it elasticsearch /usr/share/elasticsearch/bin/elasticsearch-reset-password -i -u kibana_system

# docker exec -it elasticsearch /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
# docker cp elasticsearch:/usr/share/elasticsearch/config/certs/http_ca.crt .

# docker exec -it kibana bin/kibana-verification-code
---
- name: Docker EFK deploy
  hosts: localhost
  connection: local 
  become: true
  gather_facts: false

  tasks:
    - name: Create project path for elasticsearch
      file:
        path: "../esdata"
        mode: 0755
        group: "0"
        owner: "1000"
        recurse: true
        state: directory

    - name: Create path for kibana
      file:
        path: "../kibanadata"
        mode: 0755
        group: "0"
        owner: "1000"
        recurse: true
        state: directory

    - name: Containers EFK deploy
      community.docker.docker_compose:
        project_src: ../efk-docker
        build: true
