## Deploy service golang with Ansible
# ansible-playbook playbooks/pl_efk_local.yml
---
- name: Docker EFK deploy
  hosts: localhost
  connection: local 
  become: true
  gather_facts: false

  tasks:
    - name: Create project path and subfolder for container
      file:
        path: "../esdata"
        mode: 0755
        group: "0"
        owner: "1000"
        recurse: true
        state: directory

    - name: Container Grafana deploy
      community.docker.docker_compose:
        project_src: ../efk-docker

