---
# defaults file for setup_efk_docker

must_efk_installed: false
must_ek_installed: false
must_f_installed: false

# Sate Specifying 'present' is the same as running docker-compose up resp or 
# 'absent' is the same as running docker-compose down.
efk_docker_state: present

# delete data if 'efk_docker_state' == 'absent'
efk_data_remove: false 

# Password for the 'elastic' user (at least 6 characters)
efk_elastic_password: R03QGNeSY9zpkcFWtVPg

# Password for the 'kibana_system' user (at least 6 characters)
efk_kibana_password: l52Fu7nprgE2+WrB510X

# Version of Elastic products
efk_stack_version: 8.5.3

# Set the cluster name
efk_cluster_name: docker-cluster

# Set to 'basic' or 'trial' to automatically start the 30-day trial
efk_license: basic
#LICENSE=trial

# Port to expose Elasticsearch HTTP API to the host
efk_es_port: 9200
#ES_PORT=127.0.0.1:9200

# Port to expose Kibana to the host
efk_kibana_port: 5601
#KIBANA_PORT=80

# Increase or decrease based on the available host memory (in bytes)
efk_mem_limit: 1073741824